### ISSUE TITLE
Issue with PCDATA

### ISSUE THREAD

**Issue by christopher5106** [bsuh/node_xslt#30]
I got this issue : 
````
parser error : PCDATA invalid Char value 3
n olivate, cera alba*, olea europaea fruit oil*, rosa damascena  flower water*, 
                                                                               ^
				var document = xslt.readXmlFile(file_name);

```

**Comment by CentaurWarchief** [comment]
Can you show your XML file?

**Comment by christopher5106** [comment]
There is a ^C (control C character) inside the one PCDATA

ml/ 2.64fl.oz.Ingredients: aqua, bentonite, glycerin, helianthus annuus seed oil*, cetearyl olivate, sorbitan olivate, cera alba*, olea europaea fruit oil*, rosa damascena  flower water*, ^Caloe barbadensis leaf  extract*, lactic acid, citric acid, parfum, citronellol, geraniol, linalool, xanthan gum, tocopherol,sodium dehydroacetate, potassium sorb
